<a href="https://colab.research.google.com/github/eslamahmed235/Arabic-dialect-classification-ML-DL/blob/main/Data_fetching_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-7vpa0W7lOtiOXCT_XxzH-63ed5Zo7jk' -O dialict.csv

--2022-03-14 17:45:14--  https://docs.google.com/uc?export=download&id=1-7vpa0W7lOtiOXCT_XxzH-63ed5Zo7jk
Resolving docs.google.com (docs.google.com)... 172.253.123.100, 172.253.123.102, 172.253.123.101, ...
Connecting to docs.google.com (docs.google.com)|172.253.123.100|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-08-1g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/1en86l1gssck20a35pmol10d6ptee4c1/1647279900000/15315052740638448697/*/1-7vpa0W7lOtiOXCT_XxzH-63ed5Zo7jk?e=download [following]
Warning: wildcards not supported in HTTP.
--2022-03-14 17:45:15--  https://doc-08-1g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/1en86l1gssck20a35pmol10d6ptee4c1/1647279900000/15315052740638448697/*/1-7vpa0W7lOtiOXCT_XxzH-63ed5Zo7jk?e=download
Resolving doc-08-1g-docs.googleusercontent.com (doc-08-1g-docs.googleusercontent.com)... 173.194.218.132, 2607:f8b0:400c:c14::84
Connecting to doc-08-1g-docs.googleusercontent.com (doc-08-1g-docs.googleusercontent.com)|173.194.218.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10339942 (9.9M) [text/csv]
Saving to: ‘dialict.csv’

dialict.csv         100%[===================>]   9.86M  65.4MB/s    in 0.2s

2022-03-14 17:45:15 (65.4 MB/s) - ‘dialict.csv’ saved [10339942/10339942]

In [2]:
import pandas as pd
import numpy as np
import requests
import json as js
from time import sleep

In [3]:
# read given dataset id and dialect columns
data_ID_Label = pd.read_csv('/content/dialict.csv',dtype='string')
data_ID_Label

                         id dialect
0       1175358310087892992      IQ
1       1175416117793349632      IQ
2       1175450108898565888      IQ
3       1175471073770573824      IQ
4       1175496913145217024      IQ
...                     ...     ...
458192  1019484980282580992      BH
458193  1021083283709407232      BH
458194  1017477537889431552      BH
458195  1022430374696239232      BH
458196  1022409931029458944      BH

[458197 rows x 2 columns]

In [4]:
# split dataset into N of lists with size 1000 to be suitable with post request requirement  

# add ID into list
data_ID_Label_list = list(data_ID_Label.id)
data_chunked_list = list()
# set size of each list
chunk_size = 1000

for i in range(0, len(data_ID_Label_list), chunk_size):
    data_chunked_list.append(data_ID_Label_list[i:i+chunk_size])

In [5]:
# define url and requrest list
round = 0
count = 0
while round < len(data_chunked_list):

  url = 'https://recruitment.aimtechnologies.co/ai-tasks'
  request = js.dumps(data_chunked_list[round])

  # send request
  response = requests.post(url, data = request)
  # sleep(1)

  # read response as json and convert to pd.dataFrame
  response_json = response.json()
  response_dataframe = pd.DataFrame(list(response_json.items()),
                        columns=['tweet_id','tweet'])

  round += 1
  count += len(response_dataframe)

  print(f"Done request no.{round} and get {count} tweets ")

 # save and append output into csv file
  with open(f'output.csv', mode='a') as f:
    response_dataframe.to_csv(f, mode ='a', header=f.tell()==0)

Done request no.1 and get 1000 tweets
Done request no.2 and get 2000 tweets
Done request no.3 and get 3000 tweets
Done request no.4 and get 4000 tweets
Done request no.5 and get 5000 tweets
Done request no.6 and get 6000 tweets
Done request no.7 and get 7000 tweets
Done request no.8 and get 8000 tweets
Done request no.9 and get 9000 tweets
Done request no.10 and get 10000 tweets
Done request no.11 and get 11000 tweets
Done request no.12 and get 12000 tweets
Done request no.13 and get 13000 tweets
Done request no.14 and get 14000 tweets
Done request no.15 and get 15000 tweets
Done request no.16 and get 16000 tweets
Done request no.17 and get 17000 tweets
Done request no.18 and get 18000 tweets
Done request no.19 and get 19000 tweets
Done request no.20 and get 20000 tweets
Done request no.21 and get 21000 tweets
Done request no.22 and get 22000 tweets
Done request no.23 and get 23000 tweets
Done request no.24 and get 24000 tweets
Done request no.25 and get 25000 tweets
Done request no.26 and get 26000 tweets
Done request no.27 and get 27000 tweets
Done request no.28 and get 28000 tweets
Done request no.29 and get 29000 tweets
Done request no.30 and get 30000 tweets
Done request no.31 and get 31000 tweets
Done request no.32 and get 32000 tweets
Done request no.33 and get 33000 tweets
Done request no.34 and get 34000 tweets
Done request no.35 and get 35000 tweets
Done request no.36 and get 36000 tweets
Done request no.37 and get 37000 tweets
Done request no.38 and get 38000 tweets
Done request no.39 and get 39000 tweets
Done request no.40 and get 40000 tweets
Done request no.41 and get 41000 tweets
Done request no.42 and get 42000 tweets
Done request no.43 and get 43000 tweets
Done request no.44 and get 44000 tweets
Done request no.45 and get 45000 tweets
Done request no.46 and get 46000 tweets
Done request no.47 and get 47000 tweets
Done request no.48 and get 48000 tweets
Done request no.49 and get 49000 tweets
Done request no.50 and get 50000 tweets
Done request no.51 and get 51000 tweets
Done request no.52 and get 52000 tweets
Done request no.53 and get 53000 tweets
Done request no.54 and get 54000 tweets
Done request no.55 and get 55000 tweets
Done request no.56 and get 56000 tweets
Done request no.57 and get 57000 tweets
Done request no.58 and get 58000 tweets
Done request no.59 and get 59000 tweets
Done request no.60 and get 60000 tweets
Done request no.61 and get 61000 tweets
Done request no.62 and get 62000 tweets
Done request no.63 and get 63000 tweets
Done request no.64 and get 64000 tweets
Done request no.65 and get 65000 tweets
Done request no.66 and get 66000 tweets
Done request no.67 and get 67000 tweets
Done request no.68 and get 68000 tweets
Done request no.69 and get 69000 tweets
Done request no.70 and get 70000 tweets
Done request no.71 and get 71000 tweets
Done request no.72 and get 72000 tweets
Done request no.73 and get 73000 tweets
Done request no.74 and get 74000 tweets
Done request no.75 and get 75000 tweets
Done request no.76 and get 76000 tweets
Done request no.77 and get 77000 tweets
Done request no.78 and get 78000 tweets
Done request no.79 and get 79000 tweets
Done request no.80 and get 80000 tweets
Done request no.81 and get 81000 tweets
Done request no.82 and get 82000 tweets
Done request no.83 and get 83000 tweets
Done request no.84 and get 84000 tweets
Done request no.85 and get 85000 tweets
Done request no.86 and get 86000 tweets
Done request no.87 and get 87000 tweets
Done request no.88 and get 88000 tweets
Done request no.89 and get 89000 tweets
Done request no.90 and get 90000 tweets
Done request no.91 and get 91000 tweets
Done request no.92 and get 92000 tweets
Done request no.93 and get 93000 tweets
Done request no.94 and get 94000 tweets
Done request no.95 and get 95000 tweets
Done request no.96 and get 96000 tweets
Done request no.97 and get 97000 tweets
Done request no.98 and get 98000 tweets
Done request no.99 and get 99000 tweets
Done request no.100 and get 100000 tweets
Done request no.101 and get 101000 tweets
Done request no.102 and get 102000 tweets
Done request no.103 and get 103000 tweets
Done request no.104 and get 104000 tweets
Done request no.105 and get 105000 tweets
Done request no.106 and get 106000 tweets
Done request no.107 and get 107000 tweets
Done request no.108 and get 108000 tweets
Done request no.109 and get 109000 tweets
Done request no.110 and get 110000 tweets
Done request no.111 and get 111000 tweets
Done request no.112 and get 112000 tweets
Done request no.113 and get 113000 tweets
Done request no.114 and get 114000 tweets
Done request no.115 and get 115000 tweets
Done request no.116 and get 116000 tweets
Done request no.117 and get 117000 tweets
Done request no.118 and get 118000 tweets
Done request no.119 and get 119000 tweets
Done request no.120 and get 120000 tweets
Done request no.121 and get 121000 tweets
Done request no.122 and get 122000 tweets
Done request no.123 and get 123000 tweets
Done request no.124 and get 124000 tweets
Done request no.125 and get 125000 tweets
Done request no.126 and get 126000 tweets
Done request no.127 and get 127000 tweets
Done request no.128 and get 128000 tweets
Done request no.129 and get 129000 tweets
Done request no.130 and get 130000 tweets
Done request no.131 and get 131000 tweets
Done request no.132 and get 132000 tweets
Done request no.133 and get 133000 tweets
Done request no.134 and get 134000 tweets
Done request no.135 and get 135000 tweets
Done request no.136 and get 136000 tweets
Done request no.137 and get 137000 tweets
Done request no.138 and get 138000 tweets
Done request no.139 and get 139000 tweets
Done request no.140 and get 140000 tweets
Done request no.141 and get 141000 tweets
Done request no.142 and get 142000 tweets
Done request no.143 and get 143000 tweets
Done request no.144 and get 144000 tweets
Done request no.145 and get 145000 tweets
Done request no.146 and get 146000 tweets
Done request no.147 and get 147000 tweets
Done request no.148 and get 148000 tweets
Done request no.149 and get 149000 tweets
Done request no.150 and get 150000 tweets
Done request no.151 and get 151000 tweets
Done request no.152 and get 152000 tweets
Done request no.153 and get 153000 tweets
Done request no.154 and get 154000 tweets
Done request no.155 and get 155000 tweets
Done request no.156 and get 156000 tweets
Done request no.157 and get 157000 tweets
Done request no.158 and get 158000 tweets
Done request no.159 and get 159000 tweets
Done request no.160 and get 160000 tweets
Done request no.161 and get 161000 tweets
Done request no.162 and get 162000 tweets
Done request no.163 and get 163000 tweets
Done request no.164 and get 164000 tweets
Done request no.165 and get 165000 tweets
Done request no.166 and get 166000 tweets
Done request no.167 and get 167000 tweets
Done request no.168 and get 168000 tweets
Done request no.169 and get 169000 tweets
Done request no.170 and get 170000 tweets
Done request no.171 and get 171000 tweets
Done request no.172 and get 172000 tweets
Done request no.173 and get 173000 tweets
Done request no.174 and get 174000 tweets
Done request no.175 and get 175000 tweets
Done request no.176 and get 176000 tweets
Done request no.177 and get 177000 tweets
Done request no.178 and get 178000 tweets
Done request no.179 and get 179000 tweets
Done request no.180 and get 180000 tweets
Done request no.181 and get 181000 tweets
Done request no.182 and get 182000 tweets
Done request no.183 and get 183000 tweets
Done request no.184 and get 184000 tweets
Done request no.185 and get 185000 tweets
Done request no.186 and get 186000 tweets
Done request no.187 and get 187000 tweets
Done request no.188 and get 188000 tweets
Done request no.189 and get 189000 tweets
Done request no.190 and get 190000 tweets
Done request no.191 and get 191000 tweets
Done request no.192 and get 192000 tweets
Done request no.193 and get 193000 tweets
Done request no.194 and get 194000 tweets
Done request no.195 and get 195000 tweets
Done request no.196 and get 196000 tweets
Done request no.197 and get 197000 tweets
Done request no.198 and get 198000 tweets
Done request no.199 and get 199000 tweets
Done request no.200 and get 200000 tweets
Done request no.201 and get 201000 tweets
Done request no.202 and get 202000 tweets
Done request no.203 and get 203000 tweets
Done request no.204 and get 204000 tweets
Done request no.205 and get 205000 tweets
Done request no.206 and get 206000 tweets
Done request no.207 and get 207000 tweets
Done request no.208 and get 208000 tweets
Done request no.209 and get 209000 tweets
Done request no.210 and get 210000 tweets
Done request no.211 and get 211000 tweets
Done request no.212 and get 212000 tweets
Done request no.213 and get 213000 tweets
Done request no.214 and get 214000 tweets
Done request no.215 and get 215000 tweets
Done request no.216 and get 216000 tweets
Done request no.217 and get 217000 tweets
Done request no.218 and get 218000 tweets
Done request no.219 and get 219000 tweets
Done request no.220 and get 220000 tweets
Done request no.221 and get 221000 tweets
Done request no.222 and get 222000 tweets
Done request no.223 and get 223000 tweets
Done request no.224 and get 224000 tweets
Done request no.225 and get 225000 tweets
Done request no.226 and get 226000 tweets
Done request no.227 and get 227000 tweets
Done request no.228 and get 228000 tweets
Done request no.229 and get 229000 tweets
Done request no.230 and get 230000 tweets
Done request no.231 and get 231000 tweets
Done request no.232 and get 232000 tweets
Done request no.233 and get 233000 tweets
Done request no.234 and get 234000 tweets
Done request no.235 and get 235000 tweets
Done request no.236 and get 236000 tweets
Done request no.237 and get 237000 tweets
Done request no.238 and get 238000 tweets
Done request no.239 and get 239000 tweets
Done request no.240 and get 240000 tweets
Done request no.241 and get 241000 tweets
Done request no.242 and get 242000 tweets
Done request no.243 and get 243000 tweets
Done request no.244 and get 244000 tweets
Done request no.245 and get 245000 tweets
Done request no.246 and get 246000 tweets
Done request no.247 and get 247000 tweets
Done request no.248 and get 248000 tweets
Done request no.249 and get 249000 tweets
Done request no.250 and get 250000 tweets
Done request no.251 and get 251000 tweets
Done request no.252 and get 252000 tweets
Done request no.253 and get 253000 tweets
Done request no.254 and get 254000 tweets
Done request no.255 and get 255000 tweets
Done request no.256 and get 256000 tweets
Done request no.257 and get 257000 tweets
Done request no.258 and get 258000 tweets
Done request no.259 and get 259000 tweets
Done request no.260 and get 260000 tweets
Done request no.261 and get 261000 tweets
Done request no.262 and get 262000 tweets
Done request no.263 and get 263000 tweets
Done request no.264 and get 264000 tweets
Done request no.265 and get 265000 tweets
Done request no.266 and get 266000 tweets
Done request no.267 and get 267000 tweets
Done request no.268 and get 268000 tweets
Done request no.269 and get 269000 tweets
Done request no.270 and get 270000 tweets
Done request no.271 and get 271000 tweets
Done request no.272 and get 272000 tweets
Done request no.273 and get 273000 tweets
Done request no.274 and get 274000 tweets
Done request no.275 and get 275000 tweets
Done request no.276 and get 276000 tweets
Done request no.277 and get 277000 tweets
Done request no.278 and get 278000 tweets
Done request no.279 and get 279000 tweets
Done request no.280 and get 280000 tweets
Done request no.281 and get 281000 tweets
Done request no.282 and get 282000 tweets
Done request no.283 and get 283000 tweets
Done request no.284 and get 284000 tweets
Done request no.285 and get 285000 tweets
Done request no.286 and get 286000 tweets
Done request no.287 and get 287000 tweets
Done request no.288 and get 288000 tweets
Done request no.289 and get 289000 tweets
Done request no.290 and get 290000 tweets
Done request no.291 and get 291000 tweets
Done request no.292 and get 292000 tweets
Done request no.293 and get 293000 tweets
Done request no.294 and get 294000 tweets
Done request no.295 and get 295000 tweets
Done request no.296 and get 296000 tweets
Done request no.297 and get 297000 tweets
Done request no.298 and get 298000 tweets
Done request no.299 and get 299000 tweets
Done request no.300 and get 300000 tweets
Done request no.301 and get 301000 tweets
Done request no.302 and get 302000 tweets
Done request no.303 and get 303000 tweets
Done request no.304 and get 304000 tweets
Done request no.305 and get 305000 tweets
Done request no.306 and get 306000 tweets
Done request no.307 and get 307000 tweets
Done request no.308 and get 308000 tweets
Done request no.309 and get 309000 tweets
Done request no.310 and get 310000 tweets
Done request no.311 and get 311000 tweets
Done request no.312 and get 312000 tweets
Done request no.313 and get 313000 tweets
Done request no.314 and get 314000 tweets
Done request no.315 and get 315000 tweets
Done request no.316 and get 316000 tweets
Done request no.317 and get 317000 tweets
Done request no.318 and get 318000 tweets
Done request no.319 and get 319000 tweets
Done request no.320 and get 320000 tweets
Done request no.321 and get 321000 tweets
Done request no.322 and get 322000 tweets
Done request no.323 and get 323000 tweets
Done request no.324 and get 324000 tweets
Done request no.325 and get 325000 tweets
Done request no.326 and get 326000 tweets
Done request no.327 and get 327000 tweets
Done request no.328 and get 328000 tweets
Done request no.329 and get 329000 tweets
Done request no.330 and get 330000 tweets
Done request no.331 and get 331000 tweets
Done request no.332 and get 332000 tweets
Done request no.333 and get 333000 tweets
Done request no.334 and get 334000 tweets
Done request no.335 and get 335000 tweets
Done request no.336 and get 336000 tweets
Done request no.337 and get 337000 tweets
Done request no.338 and get 338000 tweets
Done request no.339 and get 339000 tweets
Done request no.340 and get 340000 tweets
Done request no.341 and get 341000 tweets
Done request no.342 and get 342000 tweets
Done request no.343 and get 343000 tweets
Done request no.344 and get 344000 tweets
Done request no.345 and get 345000 tweets
Done request no.346 and get 346000 tweets
Done request no.347 and get 347000 tweets
Done request no.348 and get 348000 tweets
Done request no.349 and get 349000 tweets
Done request no.350 and get 350000 tweets
Done request no.351 and get 351000 tweets
Done request no.352 and get 352000 tweets
Done request no.353 and get 353000 tweets
Done request no.354 and get 354000 tweets
Done request no.355 and get 355000 tweets
Done request no.356 and get 356000 tweets
Done request no.357 and get 357000 tweets
Done request no.358 and get 358000 tweets
Done request no.359 and get 359000 tweets
Done request no.360 and get 360000 tweets
Done request no.361 and get 361000 tweets
Done request no.362 and get 362000 tweets
Done request no.363 and get 363000 tweets
Done request no.364 and get 364000 tweets
Done request no.365 and get 365000 tweets
Done request no.366 and get 366000 tweets
Done request no.367 and get 367000 tweets
Done request no.368 and get 368000 tweets
Done request no.369 and get 369000 tweets
Done request no.370 and get 370000 tweets
Done request no.371 and get 371000 tweets
Done request no.372 and get 372000 tweets
Done request no.373 and get 373000 tweets
Done request no.374 and get 374000 tweets
Done request no.375 and get 375000 tweets
Done request no.376 and get 376000 tweets
Done request no.377 and get 377000 tweets
Done request no.378 and get 378000 tweets
Done request no.379 and get 379000 tweets
Done request no.380 and get 380000 tweets
Done request no.381 and get 381000 tweets
Done request no.382 and get 382000 tweets
Done request no.383 and get 383000 tweets
Done request no.384 and get 384000 tweets
Done request no.385 and get 385000 tweets
Done request no.386 and get 386000 tweets
Done request no.387 and get 387000 tweets
Done request no.388 and get 388000 tweets
Done request no.389 and get 389000 tweets
Done request no.390 and get 390000 tweets
Done request no.391 and get 391000 tweets
Done request no.392 and get 392000 tweets
Done request no.393 and get 393000 tweets
Done request no.394 and get 394000 tweets
Done request no.395 and get 395000 tweets
Done request no.396 and get 396000 tweets
Done request no.397 and get 397000 tweets
Done request no.398 and get 398000 tweets
Done request no.399 and get 399000 tweets
Done request no.400 and get 400000 tweets
Done request no.401 and get 401000 tweets
Done request no.402 and get 402000 tweets
Done request no.403 and get 403000 tweets
Done request no.404 and get 404000 tweets
Done request no.405 and get 405000 tweets
Done request no.406 and get 406000 tweets
Done request no.407 and get 407000 tweets
Done request no.408 and get 408000 tweets
Done request no.409 and get 409000 tweets
Done request no.410 and get 410000 tweets
Done request no.411 and get 411000 tweets
Done request no.412 and get 412000 tweets
Done request no.413 and get 413000 tweets
Done request no.414 and get 414000 tweets
Done request no.415 and get 415000 tweets
Done request no.416 and get 416000 tweets
Done request no.417 and get 417000 tweets
Done request no.418 and get 418000 tweets
Done request no.419 and get 419000 tweets
Done request no.420 and get 420000 tweets
Done request no.421 and get 421000 tweets
Done request no.422 and get 422000 tweets
Done request no.423 and get 423000 tweets
Done request no.424 and get 424000 tweets
Done request no.425 and get 425000 tweets
Done request no.426 and get 426000 tweets
Done request no.427 and get 427000 tweets
Done request no.428 and get 428000 tweets
Done request no.429 and get 429000 tweets
Done request no.430 and get 430000 tweets
Done request no.431 and get 431000 tweets
Done request no.432 and get 432000 tweets
Done request no.433 and get 433000 tweets
Done request no.434 and get 434000 tweets
Done request no.435 and get 435000 tweets
Done request no.436 and get 436000 tweets
Done request no.437 and get 437000 tweets
Done request no.438 and get 438000 tweets
Done request no.439 and get 439000 tweets
Done request no.440 and get 440000 tweets
Done request no.441 and get 441000 tweets
Done request no.442 and get 442000 tweets
Done request no.443 and get 443000 tweets
Done request no.444 and get 444000 tweets
Done request no.445 and get 445000 tweets
Done request no.446 and get 446000 tweets
Done request no.447 and get 447000 tweets
Done request no.448 and get 448000 tweets
Done request no.449 and get 449000 tweets
Done request no.450 and get 450000 tweets
Done request no.451 and get 451000 tweets
Done request no.452 and get 452000 tweets
Done request no.453 and get 453000 tweets
Done request no.454 and get 454000 tweets
Done request no.455 and get 455000 tweets
Done request no.456 and get 456000 tweets
Done request no.457 and get 457000 tweets
Done request no.458 and get 458000 tweets
Done request no.459 and get 458197 tweets

In [6]:
text_tweet = pd.read_csv("/content/output.csv",lineterminator='\n')

In [7]:
text_tweet.duplicated(['tweet_id']).sum()

print("\n collected text_data Describtion =  ",text_tweet.describe())
print("\n collected text_data info = " ,text_tweet.info())
print ('\n size of  collected text_data =' , text_tweet.shape)
print ('\n number of dupliacted record in collected text_data =' , text_tweet.duplicated().sum())
print ('\n number of Na record in collected text_data = ' , text_tweet.isna().sum().sum())
print ('\n number of Null record in collected text_data = ' , text_tweet.isnull().sum().sum())
text_tweet.head()

 collected text_data Describtion =             Unnamed: 0      tweet_id
count  458197.000000  4.581970e+05
mean      499.327377  9.801828e+17
std       288.735644  2.006205e+17
min         0.000000  1.763257e+10
25%       249.000000  9.061398e+17
50%       499.000000  1.033492e+18
75%       749.000000  1.137399e+18
max       999.000000  1.189838e+18
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458197 entries, 0 to 458196
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  458197 non-null  int64
 1   tweet_id    458197 non-null  int64
 2   tweet       458197 non-null  object
dtypes: int64(2), object(1)
memory usage: 10.5+ MB

 collected text_data info =  None

 size of  collected text_data = (458197, 3)

 number of dupliacted record in collected text_data = 0

 number of Na record in collected text_data =  0

 number of Null record in collected text_data =  0

,Unnamed: 0,tweet_id,tweet
0,0,1175358310087892992,@Nw8ieJUwaCAAreT لكن بالنهاية .. ينتفض .. يغير .
1,1,1175416117793349632,@7zNqXP0yrODdRjK يعني هذا محسوب على البشر .. ح...
2,2,1175450108898565888,@KanaanRema مبين من كلامه خليجي
3,3,1175471073770573824,@HAIDER76128900 يسلملي مرورك وروحك الحلوه💐
4,4,1175496913145217024,@hmo2406 وين هل الغيبه اخ محمد 🌸🌺